### ISSUE TITLE
Erros na inicialização e execução.

### ISSUE THREAD

**Issue by cstiano** [SIRLab/VSS-SDK#8]
Olá, tentei usar o VSS-SDK no ubuntu 16.04.3 zerado, usando uma máquina virtual. Porém deram alguns erros na inicialização e posteriormente na execução do simulador.

Os erros da inicilização são sempre parecido com este abaixo, só mudando o target, ocorreu o mesmo para o proto e outras instâncias.

collect2: error: ld returned 1 exit status
Makefile:53: recipe for target 'release' failed
make: *** [release] Error 1

Quando fui tentar executar deu o seguinte erro:
 - EXECUCAO - 
 
[EXECUTANDO]: VSS-Simulator
 
[EXECUTANDO]: VSS-Viewer
./run.sh: line 273: ./VSS-Simulator: No such file or directory
./VSS-Viewer
make: ./VSS-Viewer: Command not found
Makefile:52: recipe for target 'run' failed
make: *** [run] Error 127

**Comment by mateusmatiazzi** [comment]
Estou com o mesmo problema no Ubuntu 14.04.3. Ao executar $./run.sh vision viewer obtenho:

cd src && ./VSS-Vision
./VSS-Viewer
make: ./VSS-Viewer: Command not found
make: *** [run] Error 127
Connecting Server Multicast Sender: tcp://*:5555
QObject::connect: No such slot MainWindow::quit()
QObject::connect:  (receiver name: 'MainWindow')
QObject::connect: No such slot MainWindow::quit()
QObject::connect:  (receiver name: 'MainWindow')

E a única janela aberta é da Vision.

**Comment by manoelstilpen** [comment]
Opa, ao rodar o ./configure.sh houve algum erro?
Parece que houve algum erro ao compilar os módulos pois os comandos não foram encontrados.

**Comment by johnfercher** [comment]
@cstiano e @mateusmatiazzi. É provavel que tenha ocorrido algum erro ao executar o **configure.sh** em ambos os casos. Tentem executar novamente, dependendo do erro é só questão de pacotes que mudaram de nome no SO.

Atualmente estamos realizando alguns upgrades no SDK em branchs secundárias. Caso vocês não necessitem do VSS-Vision nesse momento, sugiro que utilizem essas branchs, pois vamos seguir no futuro com essas versões.

**Comment by BRMateus2** [comment]
Tanto o OpenCV tem de explicitar que é a versão 2.* (testado com 2.4.13.6), quanto foi impossível de instalar o Rust no Ubuntu 14.04.... tentarei novamente de outras formas, todavia o código fonte não é compilável com o método dos scripts, que é baixar a release atual.

**Comment by johnfercher** [comment]
@BRMateus2, surgiro que você utilize as branchs cmake dos projetos. Estamos terminando de refatorar todo o SDK.

Segue um pequeno tutorial:

* Clone o repositório https://github.com/SIRLab/VSS-Core e execute o script configure.sh com permissões de administrador;
* Clone o repositório https://github.com/SIRLab/VSS-Viewer, mude para branch **oop** e execute o script configure.sh com permissões de administrador;
* Clone o repositório https://github.com/SIRLab/VSS-Simulator, mude para branch **cmake** e execute o script configure.sh com permissões de administrador;
* Clone o repositório https://github.com/SIRLab/VSS-Joystick, mude para branch **cmake** e execute o script configure.sh com permissões de administrador;
* Clone o repositório https://github.com/SIRLab/VSS-Vision, mude para branch **cmake** e execute o script configure.sh com permissões de administrador;

Depois de fazer todos esses passos, você vai ter instalado a biblioteca VSS-Core e os projetos VSS-Viewer, VSS-Simulator e VSS-Joystick. Para executa-los, basta abrir um terminal para cada projeto e executar:

```
$ vss-viewer
```
```
$ vss-simulator
```
```
$ vss-joystick
```

Estamos finalizando o VSS-Vision em conjunto com a galera do Rodetas, para rodar ele. Você deve ir na pasta do repositório, dentro da pasta build e rodar o executável:
```
$ ./vss-vision
```

Temos um exemplo de como escrever uma estratégia para se comunicar com o VSS-SDK. Está nesse repositório https://github.com/SIRLab/VSS-SampleCpp. Para utilizar o VSS-Core atualizado com as novas funcionalidades, você deve utilizar a branch cmake também.

**Se você tiver problema em instalar o VSS-Simulator, me avise. Caso esteja rodando uma distro linux antiga, vai ter que instalar a biblioteca bullet na mão.**

**Comment by Maxsfelp** [comment]
@johnfercher Segui esse método que você passo de clona todos separados e tudo ocorreu bem exceto com o VSS-Vision e com o VSS-Joystick que deu erro no joystick deu esse erro CommandSender.h: Arquivo ou diretório não encontrado e no vision deu esse State.h: Arquivo ou diretório não encontrado se puder me ajudar ficarei grato!

**Comment by johnfercher** [comment]
@Maxsfelp, quanto ao **VSS-Joystick** acabei de subir um correção. Da git pull e roda novamente o **configure.sh**. Estamos vendo agora o problema do VSS-Vision.

**Comment by johnfercher** [comment]
@Maxsfelp, subi a mesma correção para o **VSS-Vision**, se puder testar e me falar se funcionou.

**Comment by Maxsfelp** [comment]
o VSS-Joystick funcionou vou testar o VSS-Vision

**Comment by Maxsfelp** [comment]
aquele erro foi corrigido agora apareceu esse Robot.h: Arquivo ou diretório não encontrado

**Comment by johnfercher** [comment]
@Maxsfelp , atualiza novamente o **VSS-Vision** e roda o **configure.sh**

**Comment by Maxsfelp** [comment]
agora foi Ball.h: Arquivo ou diretório não encontrado

**Comment by johnfercher** [comment]
@Maxsfelp , testa novamente. Se ocorrer um erro, me mande uma cópia dele aqui por favor.

**Comment by Maxsfelp** [comment]
copia dele o que exatamente ?

**Comment by Maxsfelp** [comment]
Ocorreu tudo certo, muito obrigado pela ajuda
